version: '3'
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    volumes:
      - .:/terraform
      - ~/.aws:/root/.aws
    working_dir: /terraform/terraform
    entrypoint: ash
    tty: true
